root: true
extends:
  - plugin:markdown/recommended
plugins:
  - markdown
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
rules:
  eol-last: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-mixed-spaces-and-tabs: error
  no-trailing-spaces: error
